version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - "${VOLUME_ROOT_PATH}/zookeeper/log:/var/lib/zookeeper/log"
      - "${VOLUME_ROOT_PATH}/zookeeper/data:/var/lib/zookeeper/data"
    networks:
        - kafka-local-network
  kafka_broker_1:
    container_name: kafka_broker_1
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "19092:19092" 
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      KAFKA_BROCKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker_1:19092,EXTERNAL://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - "${VOLUME_ROOT_PATH}/kafka_1/data:/var/lib/data"
    depends_on:
      - zookeeper
    networks:
      - kafka-local-network
  kafka_broker_2:
    container_name: kafka_broker_2
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9093"
      - "29092:29092" 
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      KAFKA_BROCKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker_2:29092,EXTERNAL://127.0.0.1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - "${VOLUME_ROOT_PATH}/kafka_2/data:/var/lib/data"
    depends_on:
      - zookeeper
    networks:
      - kafka-local-network
 
networks:
  kafka-local-network:
